Feat: Contact page working.
zurichat/zc_main pull request #2501
Opened 2022-11-07 01:22 UTC by Harrylever

Contact Page working. Disabled `getuserinfo` function from Contact Form Component, user Email Address entered manually. Modified user.js, not return error upon user not join organisation or workspace yet.

2022-11-11 15:59 UTC, JulianaSau commented
@Harrylever resolve the conflicts on your branch and include an image or video showing how the component looked before and how it looks after your implemented changes

2022-11-12 04:23 UTC, Harrylever commented
Just seeing this now would start working on it right away.

2022-11-12 04:24 UTC, Harrylever commented
@JulianaSau Just saw this now would start working on it right away.

2022-11-12 09:34 UTC, JulianaSau requested changes
Okay. Also, when you're done, could you provide a video demonstrating how it works now that you've fixed it

2022-11-12 09:34 UTC, JulianaSau commented on packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx
> -  }, []);
Please explain why you removed this code and what code you added to substitute this functionality. I'm trying to see the thought process behind this and why this code would not work

2022-11-24 09:45 UTC, closed without merging