ZUR-101 My PR Reduce the gap in the profile dropdown
zurichat/zc_main pull request #2551
Opened 2022-11-10 20:01 UTC by mo-gbolahan

Reduce the gap in the profile dropdown -close ZUR-101-

2022-11-11 18:13 UTC, JulianaSau commented
@mo-gbolahan Please include videos/screenshots of the component before you made your changes and after you made your changes.

2022-11-11 18:16 UTC, JulianaSau requested changes

2022-11-11 18:16 UTC, JulianaSau commented on packages/main/src/components/protected/topbar/styles/Topbar.module.css
> +  /* margin: 0.5rem 0; */
Instead of commenting out the changes, if the code is not in use\ remove it entirely from the file

2022-11-11 19:07 UTC, mo-gbolahan commented
![after](https://user-images.githubusercontent.com/31252159/201412942-028b9a48-7b1c-4029-96ec-2f8fb078fd5f.png)
![before](https://user-images.githubusercontent.com/31252159/201412953-d6759d67-856e-432d-a648-419de08bc8d0.png)

2022-11-11 19:08 UTC, mo-gbolahan commented
![before](https://user-images.githubusercontent.com/31252159/201413022-1520a1a7-c290-48ad-a335-93d54aeafc63.png)
before
![after](https://user-images.githubusercontent.com/31252159/201413049-f2e68bb1-420d-413a-a83e-c477a1c95b25.png)
after

2022-11-11 20:00 UTC, JulianaSau commented
You've removed some very necessary space after the sign out button. Otherwise the other spacings look good @mo-gbolahan

2022-11-11 20:13 UTC, mo-gbolahan commented
I've adjusted the space below the sign out btn
![after](https://user-images.githubusercontent.com/31252159/201424323-996bf2f4-0a43-473d-a00f-9f3e4757db51.png)
after
![space below sign out](https://user-images.githubusercontent.com/31252159/201424349-a8e1aad7-1718-48a5-a74a-62af8d2e1dba.png)
space below sign out btn

2022-11-11 23:08 UTC, JulianaSau commented
Add some more space. It should match the space that is above the text 'hormorgborlarhan'
When you're done tag me to review

2022-11-12 07:54 UTC, mo-gbolahan commented
![Screenshot (44)](https://user-images.githubusercontent.com/31252159/201464572-a1eeb284-29a3-4563-a73c-b5f346110c64.png)

adjusted the space below the signout btn

2022-11-12 08:27 UTC, JulianaSau approved these changes

2022-11-12 18:54 UTC, JulianaSau commented
@mo-gbolahan pull changes from the dev branch so that i can merge your pr

2022-11-12 19:15 UTC, merged