Login Page Font Mismatch Fix
zurichat/zc_main pull request #2555
Opened 2022-11-10 21:02 UTC by efunnuga-bamidele

Applied Lato Font to the Login Page and all other elements on the page, also made use of the !Important  CSS tag to override any other font style on the page.

2022-11-11 18:33 UTC, JulianaSau requested changes

2022-11-11 18:33 UTC, JulianaSau commented on packages/main/src/pages/login/Login.module.css
> +  /* font-family: "Lato", sans-serif; */
If the code is not being used, you should do away with it entirely instead fo commenting it out

2022-11-11 18:40 UTC, JulianaSau commented on packages/main/src/pages/login/Login.module.css
> +  /* font-family: "Lato", sans-serif; */
Also, ensure you add screenshots of the component before and after your changes

2022-11-11 18:52 UTC, efunnuga-bamidele commented
Code Before Changes
![image](https://user-images.githubusercontent.com/60141949/201410469-4484d15d-f413-4f1d-bb35-e2a57ea851e5.png)

Code After Changes
![image](https://user-images.githubusercontent.com/60141949/201410671-522e254b-16a8-4b9f-901a-e9df4a7220c1.png)

2022-11-11 18:56 UTC, JulianaSau commented
I mean screenshots of the page itself @efunnuga-bamidele. The code is okay.

2022-11-11 19:25 UTC, efunnuga-bamidele commented
Before Code Change
![image](https://user-images.githubusercontent.com/60141949/201415206-e79fd35b-1e56-4c99-b2bd-690ac40637f6.png)


After Code Change
![image](https://user-images.githubusercontent.com/60141949/201415431-c75efd99-e7b9-49e6-ada6-a7a5324f0725.png)

2022-11-11 19:39 UTC, JulianaSau approved these changes
Looks good

2022-11-11 20:46 UTC, billmal071 commented
I don't see why you need to use !important, can you look at the style affecting it and removing so that there won't be a need to use important.

2022-11-12 12:39 UTC, efunnuga-bamidele commented
@billmal071, changes implemented
Before Changes
![before](https://user-images.githubusercontent.com/60141949/201474267-d5b8c0de-dd93-4dc2-a388-1657d26771ee.PNG)

After Changes
![after](https://user-images.githubusercontent.com/60141949/201474270-885819e1-c355-4daa-848f-6e8d2810d04f.PNG)

2022-11-13 20:13 UTC, JulianaSau commented
@efunnuga-bamidele pull changes from the dev branch and push them to your remote repository

2022-11-13 21:49 UTC, merged