Feat/deactivate send chat button when chatbox is empty
zurichat/zc_main pull request #2573
Opened 2022-11-11 13:17 UTC by Gelaraph

I disabled the send button on the chatbox editor when the editor/input field is empty and so the user can't click on the button unless there is text, an emoji, or a file in the field and the the button gets enabled.

2022-11-11 14:03 UTC, billmal071 commented
Ptovide a video showing that it works.

2022-11-11 19:04 UTC, Gelaraph commented
https://user-images.githubusercontent.com/91147803/201412412-72628c08-ca29-4e01-81eb-f1d24ca68b2c.mp4

2022-11-11 20:33 UTC, JulianaSau requested changes
You can remove the commented-out code. Otherwise, everything else looks good

2022-11-11 20:33 UTC, JulianaSau commented on packages/ui/src/message-pane-input/MessagePaneInput.jsx
> +  // console.log("field", editorState);
If the code isn't being used, instead of commenting it out you could do away with it entirely

2022-11-11 20:33 UTC, JulianaSau commented on packages/ui/src/message-pane-input/components/Toolbar.jsx
> +  // const inputLength = editorState.getData();
Same to these commented out codes

2022-11-11 20:46 UTC, Gelaraph commented
Alright, I'll remove them. Thanks.

2022-11-11 20:52 UTC, Gelaraph commented
Changes have been made and pushed.

2022-11-11 21:07 UTC, JulianaSau approved these changes

2022-11-11 22:19 UTC, billmal071 commented
Pull latest code and push.

2022-11-13 17:58 UTC, JulianaSau commented
Pull changes from dev branch, Resolve conflicts and push the updates to your repo @Gelaraph so that i can merge

2022-11-14 08:20 UTC, Gelaraph commented
I have pulled and committed recent changes.

2022-11-14 08:26 UTC, merged