ZUR-153 My PR removes all import leading to the src-old folder and also all unused refs #2567 and also Fixed commit
zurichat/zc_main pull request #2592
Opened 2022-11-11 21:18 UTC by sulaimon23

2022-11-11 21:20 UTC, sulaimon23 commented
@JulianaSau Here is the updated push with the proper commit history

2022-11-11 22:10 UTC, JulianaSau requested changes
Why did you delete the `yarn.lock`?
Since it's already in the codebase, you can just let it be. Don't modify it in any way

2022-11-12 08:26 UTC, sulaimon23 commented
@JulianaSau done. Thanks

2022-11-12 10:03 UTC, JulianaSau requested changes
I'd suggest creating a fresh pr that isn't modifying the yarn.lock file, no changes on dependencies in the repo.
Just work on the files you were asked to change and commit only those changes

2022-11-12 10:03 UTC, JulianaSau commented on package.json
> +    "webpack": "^5.75.0"
Are these dependencies you're adding related to the task you were given?

2022-11-12 10:03 UTC, JulianaSau commented on packages/main/webpack.config.js
> +          include: [path.resolve(__dirname, "not_exist_path")],
Same to this

2022-11-12 10:03 UTC, JulianaSau commented on packages/marketplace/webpack.config.js
> +          include: [path.resolve(__dirname, "not_exist_path")],
Same to this

2022-11-12 10:03 UTC, JulianaSau commented on packages/ui/webpack.config.js
> +          include: [path.resolve(__dirname, "not_exist_path")],
Same to this

2022-11-12 10:10 UTC, sulaimon23 commented
okay thanks
@JulianaSau

2022-11-12 10:13 UTC, closed without merging