ZUR-184 feat: ability to react to messages and images in rooms
zurichat/zc_main pull request #2612
Opened 2022-11-12 23:21 UTC by Johndiddles

2022-11-12 23:25 UTC, JulianaSau commented
@tundealabi
Should this change be done in `zc_main` or `zc_messaging`?

2022-11-12 23:33 UTC, tundealabi commented
> @tundealabi Should this change be done in `zc_main` or `zc_messaging`?

both

2022-11-12 23:40 UTC, JulianaSau commented
Okay. Is it working on your end now? I saw some message reactions when testing other prs on local.

2022-11-12 23:43 UTC, tundealabi commented
> Okay. Is it working on your end now? I saw some message reactions when testing other prs on localhost.

those reactions have been there

2022-11-13 04:56 UTC, Johndiddles commented
@tundealabi I am not sure you have taken a look at it.......those reactions were not there until I worked on it.

2022-11-13 11:27 UTC, tundealabi commented
message duplicates when adding/removing an emoji
<img width="1440" alt="Screenshot 2022-11-13 at 12 26 34" src="https://user-images.githubusercontent.com/61058516/201519277-3e907af7-e62f-4c6d-9183-80fcad8257d3.png">

2022-11-13 16:32 UTC, JulianaSau commented
@Johndiddles have you noted this?

2022-11-13 17:20 UTC, Johndiddles commented
@JulianaSau Yes, I just did a patch on both zc_main and zc_messaging for the suggestion @tundealabi mentioned earlier.

2022-11-13 17:21 UTC, JulianaSau commented
Add a video showing that it's not duplicating again

2022-11-13 17:35 UTC, Johndiddles commented
@JulianaSau @tundealabi 

https://user-images.githubusercontent.com/48492384/201535791-e29c57d6-c557-401a-b973-ab76107f84b8.mp4

2022-11-13 19:21 UTC, tundealabi commented on packages/ui/src/message-board/MessageBoard.jsx
> +  console.log({ messages });
remove the console.log. thanks

2022-11-13 19:51 UTC, Johndiddles commented
@tundealabi console.log has been removed. thanks

2022-11-13 19:52 UTC, tundealabi submitted a review, later dismissed
can you remove the comments? thanks

2022-11-13 19:53 UTC, tundealabi commented on packages/ui/src/message-board/MessageBoard.jsx
> +  // messages = Array.from(new Set(messages.map(a => a._id))).map(id => {
comments here

2022-11-13 19:53 UTC, tundealabi commented on packages/ui/src/message-pane/MessagePane.jsx
> +  // console.log({ message });
comments here

2022-11-13 19:59 UTC, Johndiddles commented on packages/ui/src/message-board/MessageBoard.jsx
> +  // messages = Array.from(new Set(messages.map(a => a._id))).map(id => {
Done

2022-11-13 19:59 UTC, Johndiddles commented on packages/ui/src/message-pane/MessagePane.jsx
> +  // console.log({ message });
Done

2022-11-13 20:00 UTC, Johndiddles commented
all console.logs have been removed.....thanks

2022-11-13 20:03 UTC, tundealabi commented on packages/ui/src/message-pane/MessagePane.jsx
> +  // console.log({ message });
still see a comment here

2022-11-13 20:04 UTC, tundealabi commented on packages/ui/src/message-pane/MessagePane.jsx
> +  // console.log({ message });
// console.log({ message });

2022-11-13 20:06 UTC, JulianaSau requested changes
Your pr is changing the `yarn.lock` file.
Updating this file could affect other contributors so please remove it from your commits

2022-11-13 20:50 UTC, Johndiddles commented
yarn.lock has been removed and added to .gitignore

2022-11-13 20:55 UTC, JulianaSau commented
> yarn.lock has been removed and added to .gitignore

Don't add the lock file to `.gitignore`, just ensure you don't modify it at all. The lock file in the repo should be the same as the lock file you have on your ◀️ cal repository

2022-11-13 21:18 UTC, JulianaSau commented
Deleting them still qualifies as modification 😅😅😅
Check your changed files in this or. You'll see that you've modified the lock files

2022-11-14 04:39 UTC, Johndiddles commented
I didn't delete the lock files 😂. I untracked them, so it appeared in the history as deleted. now that I have added them back to the track but made sure they are the same with what is on the zc_main repo, they are appearing as additions. But I made sure they are exactly the same with what is on the repo

2022-11-14 04:50 UTC, JulianaSau approved these changes

2022-11-14 04:57 UTC, JulianaSau requested changes

2022-11-14 04:57 UTC, JulianaSau commented on packages/ui/src/message-pane/MessagePane.jsx
> +  // console.log({ message });
Remove this console.log

2022-11-14 07:12 UTC, Johndiddles commented
console.log has been removed.

2022-11-14 07:46 UTC, JulianaSau approved these changes

2022-11-14 07:52 UTC, merged