Fix/profilepic be fix
zurichat/zc_main pull request #2618
Opened 2022-11-13 12:42 UTC by Ademola101

This Pull Request is to fix the connection of the change profile picture by the user to the backend. The changed profile picture do not reflect currently on the FE.

After navigating the codebase and start the debugging process, I realize there was a problem with  response sent from the server upon the PATCH request . It show that the image link generated by the backend is 'not found"

![Screenshot 2022-11-11 095214](https://user-images.githubusercontent.com/54910756/201522126-efb6d796-cb38-4c40-9352-9dea405e9d57.png)

2022-11-15 17:08 UTC, Ademola101 commented
This further commit fix the display issue when the user upload profile picture. The default Avatar is not updated 

This is what happen when user upload picture (BEFORE)
![localhost_9000_workspace_636e91bc4746182adae9714c_plugin-chat_636e91c34746182adae9714f](https://user-images.githubusercontent.com/54910756/201981892-82bf9fb8-8028-4684-9f87-b2b8ca7c2700.png)



After the fix


![localhost_9000_workspace_636e91bc4746182adae9714c_plugin-chat_636e91c34746182adae9714f (1)](https://user-images.githubusercontent.com/54910756/201982203-2ff7e9d5-b6f5-41e8-bc7d-59d861db621f.png)

2022-11-16 12:06 UTC, JulianaSau requested changes
Remove all console.logs from your code and any commented out code

2022-11-16 12:06 UTC, JulianaSau commented on packages/main/src/components/protected/topbar/components/EditProfile.jsx
> +  console.log(userProfileImage);
Remove this console.log from here

2022-11-16 12:06 UTC, JulianaSau commented on packages/main/src/components/protected/topbar/components/EditProfile.jsx
> +                        // ref={avatarRef}
Remove this too

2022-11-16 12:06 UTC, JulianaSau commented on packages/main/src/components/protected/topbar/components/EditProfile.jsx
> +    console.log(file);
remove this code too

2022-11-16 12:06 UTC, JulianaSau commented on packages/main/src/components/protected/topbar/components/EditProfile.jsx
> +        // }
Remove this too

2022-11-16 12:06 UTC, JulianaSau commented on packages/main/src/components/protected/topbar/components/EditProfile.jsx
> +      console.log(imageReader);
Remove this code

2022-11-16 12:06 UTC, JulianaSau commented on packages/main/src/components/protected/topbar/components/EditProfile.jsx
> +      console.log(formData.get("image"));
Remove this too

2022-11-16 12:06 UTC, JulianaSau commented on packages/main/src/components/protected/topbar/components/EditProfile.jsx
> +          // setUserProfileImage(newUploadedImage);
remove this too

2022-11-16 13:39 UTC, JulianaSau approved these changes

2022-11-16 13:47 UTC, merged