Zur 167 add members list for the channel members
zurichat/zc_main pull request #2625
Opened 2022-11-14 07:22 UTC by YussaMoney

Added members list for the channel members. When a channel is clicked, a popup modal is displayed where someone can views all members of a channel.

![Screenshot (48)](https://user-images.githubusercontent.com/90405449/201598825-33c1a953-cb32-40c0-8902-aabe19f0b1fc.png)

2022-11-14 07:32 UTC, JulianaSau requested changes
Instead of showing dummy members on that modal, ensure that if the data is being fetched, i renders something like 'loading...' or no channel members yet.
All those channels have members. For a channel to exist, threr only has to be one member present so there's no need for the dummy data to appear

2022-11-14 07:32 UTC, JulianaSau commented on packages/main/src/auth/use-auth.js
> +    console.log(data.user.token);
Remove this console.log

2022-11-14 18:25 UTC, YussaMoney commented
Changes made

2022-11-14 18:52 UTC, JulianaSau requested changes
![image](https://user-images.githubusercontent.com/49183775/201741658-664ed375-77bc-4acc-baf0-df0350a7bcde.png)
This code renders a dummy member list by default. edit this so that it doesnt show the dummy list. if the data is fetching, it should display a loader or indicate that the data is beiing fetched

2022-11-15 21:00 UTC, JulianaSau commented
@YussaMoney, provide a video showing how it's working now

2022-11-16 16:40 UTC, JulianaSau commented
> I don' t have a video

That just means go and screen record one and post it here. I need to see that it's working properly now before I merge

2022-11-16 17:01 UTC, closed without merging