fixed positioning and alignment in dropdown when you click workspace …
zurichat/zc_main pull request #2636
Opened 2022-11-14 18:06 UTC by siafromspace

…name

# Fixes Issue

My PR Fixes ID-110

## What were you told to do ?

Fix alignment and positioning in dropdown when I click workspace name.

## What did you do ?

I added a negative margin top property to the ModalComponentStyles file to lift the dropdown container to match that of slack. I also commented out some code in the MessageRoomViewHeader file that caused the channel name to appear twice.

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/ Videos

Before Fixing
![PHOTO-2022-11-14-18-27-42](https://user-images.githubusercontent.com/101575004/201733005-321b2497-5c6b-4940-a9cc-8a8ec8fe349c.jpg)

How the fix should look like
![PHOTO-2022-11-14-18-27-57](https://user-images.githubusercontent.com/101575004/201732756-5b0a58ab-e8a6-43c6-8fc5-14ae3291f3a7.jpg)

After fixing
![PHOTO-2022-11-14-18-27-25](https://user-images.githubusercontent.com/101575004/201732834-2ea89901-6278-4712-8a55-ed76c11db48e.jpg)

2022-11-14 18:36 UTC, JulianaSau requested changes
The modal should line up with the first letter of the workspace name. So you can move it a bit to the left to line them up.
For the changes below, since the commented out code isn't needed, you can just remove it altogether

2022-11-14 18:36 UTC, JulianaSau commented on packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx
>              {props.name.split("#").join("# ")}
Remove this code entirely since it has no use there

2022-11-14 18:36 UTC, JulianaSau commented on packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx
> +          </span> */}
Remove this too

2022-11-14 20:24 UTC, siafromspace commented
Changes resolved.
I aligned the dropdown to first letter of workspace name and I removed the unnecessary code.

![unnamed](https://user-images.githubusercontent.com/101575004/201758465-f6b8b147-0479-4bf2-ac2f-bda70d717bd1.jpg)

2022-11-15 09:51 UTC, ickynavigator approved these changes

2022-11-15 09:58 UTC, JulianaSau approved these changes

2022-11-15 10:04 UTC, ickynavigator commented
@siafromspace update your PR title

2022-11-15 10:52 UTC, siafromspace commented
> @siafromspace update your PR title

done.

2022-11-15 10:57 UTC, merged