(FRO-35): developed the about us page on zurichat
zurichat/zc_main pull request #2690
Opened 2022-11-25 10:40 UTC by CyberGeni

# Fixes Issue/Linear Ticket
Resolves ticket [FRO-35](https://linear.app/mechanic-team-prybar/issue/FRO-35/about-us)

**My PR Fixes FRO-35**

# Changes proposed

## What were you told to do?

I was assigned to work on linear ticket fro-35-about-us which involves developing the about us page
## What did you do?

I developed the about page according to a new design already vetted and reviewed. 
I adapted to using CSS Modules for page styling
I tried to ensure responsiveness across multiple screens
I used reusable components to make the code less bulky

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos
![image](https://user-images.githubusercontent.com/70205370/203965049-b5d5f843-b64a-42bc-aaf4-68110cdcb14c.png)

2022-11-25 18:15 UTC, JulianaSau requested changes

2022-11-25 18:21 UTC, CyberGeni commented on packages/main/src/pages/static/about/index.jsx
> +            </p> */}
done

2022-11-25 20:58 UTC, JulianaSau approved these changes

2022-11-25 20:59 UTC, JulianaSau commented
Hi @CyberGeni, please resolve your conflicts so that I can merge

2022-11-26 00:25 UTC, CyberGeni commented
@JulianaSau i've fixed the merge conflict

2022-11-26 16:02 UTC, billmal071 commented
You have more conflicts.

2022-11-27 07:01 UTC, ickynavigator requested changes
I am closing this PR because there are way too many things done wrongly

2022-11-27 07:01 UTC, ickynavigator commented on packages/ui/src/message-pane-input/MessagePaneInput.jsx
> +            <img src={preview} alt="Image Preview" />
what happens if it's not an image?

2022-11-27 07:02 UTC, closed without merging

2022-11-27 07:23 UTC, CyberGeni commented
@ickynavigator 99% of these changes here weren't made by me, they're from other PRs I pulled. I'm only responsible for the changes made to the About us page, that's the feature I was assigned to.

2022-11-28 05:43 UTC, JulianaSau commented
@CyberGeni make a new or that contains only the changes you made