Feat/thread sidebar implementation
zurichat/zc_main pull request #2695
Opened 2022-11-25 17:42 UTC by Ginohmk

- Configure click on HoverItem component for opening thread
-

2022-11-25 19:59 UTC, ickynavigator requested changes

2022-11-25 19:59 UTC, ickynavigator commented on package.json
> +  },
remove this package from here

2022-11-25 19:59 UTC, ickynavigator commented on packages/main/src/components/protected/sidebar/styles/Sidebar.module.css
> +  /* line-height: 28px; */
remove the commented styles

2022-11-25 19:59 UTC, ickynavigator commented on packages/root-config/src/assets/plugin.importmap.json
> +    "@zuri/zuri-plugin-messaging": "http://localhost:5013/zuri-messaging.js"
change this back to the original url

2022-11-25 19:59 UTC, ickynavigator commented on packages/ui/src/message-board/MessageBoard.styled.js
> +  height: calc(92vh);
what is this calculating?

2022-11-25 19:59 UTC, ickynavigator commented on packages/ui/src/message-pane/components/hover-items/HoverItems.jsx
> +  const { id, handleShowMoreOptions, handleShowEmoji, navThrend } = props;
rename this prop
shouldn't it be `navThread`?

2022-11-25 19:59 UTC, ickynavigator commented on packages/ui/package.json
> +    "react-router-dom": "6",
why is react router dom installed here and why is it a different version

2022-11-25 19:59 UTC, ickynavigator commented on packages/ui/package.json
> +    "eslint-plugin-cypress": "^2.12.1",
why did you add this plugin?

2022-11-25 19:59 UTC, ickynavigator commented on packages/main/package.json
> +    "react-router-dom": "5.2.0",
why is this being downgraded?

2022-11-26 14:04 UTC, JulianaSau commented
@Ginohmk fix your conflicts please and work on the requested changes.
Also, as i stated before, a pr without a proper title and the recommended template will not be merged. Check out other prs to see how they structured their pull request descriptions

2022-11-26 14:17 UTC, Ginohmk commented
@JulianaSau , From our chat on slack, another team is implementing this project task. you asked the other team and me, to work together on this. so I am collaborating with them and using their branch now. That being said this branch is no longer used.

2022-11-26 15:48 UTC, JulianaSau commented
Okay. Let me close it then

2022-11-26 15:48 UTC, closed without merging