feat:(FE-43): redesign the sidebar for the chats pages
zurichat/zc_main pull request #2704
Opened 2022-11-26 02:34 UTC by abel-otegbola

# Fixes Issue/Linear Ticket

( This could be an existing issue or a linear ticket )

**My PR Closes #issue_number_here** or
**My PR Fixes ID-linear_ticket_number_here**

# Changes proposed

## What were you told to do?

Redesign the chats page

## What did you do?

Changed and updated the styles of the sidebar to the new design

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

2022-11-26 15:46 UTC, JulianaSau requested changes
The spacing between the components is a bit too much

2022-11-26 15:46 UTC, JulianaSau commented on packages/main/src/pages/protected/workspace/Workspace.style.js
> +>>>>>>> 564b27d1797c64e77f236414f4be6579f3d0d4b3
Resolve these conflicts

2022-11-27 07:14 UTC, ickynavigator approved these changes
remove unnecessary change

2022-11-27 07:14 UTC, ickynavigator commented on packages/main/src/components/protected/sidebar/components/Sidebar.jsx
> +
why?

2022-11-27 07:39 UTC, ickynavigator approved these changes

2022-11-27 07:58 UTC, JulianaSau approved these changes

2022-11-27 08:02 UTC, merged