corrected styling in profile section
zurichat/zc_main pull request #2710
Opened 2022-11-26 20:27 UTC by IromIbe

# Fixes Issue/Linear Ticket

( This could be an existing issue or a linear ticket )

**My PR Closes #issue_number_here** or
**My PR Fixes ID-linear_ticket_number_here**

# Changes proposed

## What were you told to do?
correct some styling bugs noticed on the profile section.

## What did you do?

I worked on the profile.jsx component and profile.module.css 
commented the section where the social icons was displayed on the dom.
made alignment corrections on the name in profile section.
# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

![zuri](https://user-images.githubusercontent.com/94483528/204107824-67a82313-e903-4eec-aafe-ff12f6c981e2.PNG)

![zuri old](https://user-images.githubusercontent.com/94483528/204107801-3fa37e85-cc90-4e1d-a975-1f438d1c57a9.PNG)

2022-11-26 22:03 UTC, billmal071 requested changes

2022-11-26 22:03 UTC, billmal071 commented on packages/main/src/components/protected/topbar/components/Profile.jsx
> +        {/* <div className={styles.social}>
If this is commented out and not needed, you can remove it.

2022-11-26 22:03 UTC, billmal071 commented on packages/main/src/components/protected/topbar/styles/Profile.module.css
> +  /* margin-right: -1em; */
remove if it's fixed.

2022-11-26 22:03 UTC, billmal071 commented on packages/main/src/components/protected/topbar/styles/Profile.module.css
> +  /* right: 70px; */
remove commented out code.

2022-11-26 22:03 UTC, billmal071 commented on packages/main/src/components/protected/topbar/styles/Profile.module.css
> +  margin: 10px 1px 10px !important;
Why use !important? You can look for what's affecting the style and fix it.

2022-11-26 22:23 UTC, JulianaSau commented
This profile component should appear just as threads does. It should not sit on top of the message board. Rather, it should be within the right space of the message board. 

Also, why is the profile modal not closing once a user clicks on view profile?

2022-11-27 05:52 UTC, IromIbe commented
made corrections as requested by the reviewer

2022-11-27 07:18 UTC, ickynavigator approved these changes

2022-11-27 08:03 UTC, IromIbe commented
i've fixed merge conflicts

2022-11-27 10:45 UTC, merged