implemented designs
zurichat/zc_main pull request #2749
Opened 2022-11-28 17:50 UTC by Izcomayana

# Fixes Issue/Linear Ticket

( This could be an existing issue or a linear ticket )

**My PR Closes #issue_number_here** or
**My PR Fixes ID-linear_ticket_number_here**

# Changes proposed

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

2022-11-29 15:57 UTC, JulianaSau commented
Fix conflicts

2022-11-29 15:58 UTC, JulianaSau commented
Why is the page so dull? Like there should be some green there like the other modals in Zuri Chat.
Black and white are not the only colors that exist🥲🥲🥲

2022-11-29 16:01 UTC, JulianaSau requested changes
You've also added so many svgs when we have an icon library called `react-icons` that contains all of these. Please try as much as possible to use available icons and not add all those svgs

2022-11-30 10:32 UTC, Izcomayana commented
> Why is the page so dull? Like there should be some green there like the other modals in Zuri Chat. Black and white are not the only colors that exist🥲🥲🥲

2022-11-30 12:50 UTC, Izcomayana commented on packages/main/src/App.js
> +  WhyZuri,
It was a mistake and I have rectify it

2022-11-30 12:51 UTC, Izcomayana commented
> Why is the page so dull? Like there should be some green there like the other modals in Zuri Chat. Black and white are not the only colors that exist🥲🥲🥲

That was how the design looked and there are some green in those pages too

2022-12-03 06:47 UTC, JulianaSau commented
Resolve conflicts so that i can review again
And please send a figma link to the redesign that your team did. @Izcomayana

2022-12-03 21:35 UTC, ickynavigator requested changes

2022-12-03 21:35 UTC, ickynavigator commented on packages/main/src/pages/preferences/assets/css/main.css
> +/* @import { FaStar } from "react-icons/fa"; */
remove comment

2022-12-03 21:35 UTC, ickynavigator commented on packages/main/src/pages/preferences/assets/css/main.css
> +  background-image: url(../images/checkbox.png);
these images are not necessary
the box can be styled that way

2022-12-03 21:35 UTC, ickynavigator commented on packages/main/src/pages/preferences/components/Appearance.js
> +                <img src={darkMode} alt="" className="w-100" />
add a descriptive alt

2022-12-03 21:35 UTC, ickynavigator commented on packages/main/src/pages/preferences/components/Appearance.js
> +                <img src={whiteMode} alt="" className="me-5 w-100" />
add a descriptive alt

2022-12-03 21:35 UTC, ickynavigator commented on packages/main/src/pages/preferences/components/Notifications.js
> +import "../assets/css/main.css";
use modules

2022-12-03 21:35 UTC, ickynavigator commented on packages/main/src/pages/preferences/index.js
> +  const accessibility = () => {
what happens when someone wants to add a new preference type?
Do they have to add a setState to all the functions?

change this and use a single object to store all the states
you can now loop through the object and change everything to false except the one you want to update

2022-12-04 19:29 UTC, closed without merging