Fro 46 channels
zurichat/zc_main pull request #2752
Opened 2022-11-29 12:18 UTC by sir-ojay

# Fixes Issue/Linear Ticket

( This could be an existing issue or a linear ticket )

**My PR Closes #issue_number_here** or
**My PR Fixes ID-linear_ticket_number_here**

# Changes proposed

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
- [] I am making a pull request against the **dev branch** (left side).
- [] My commit messages styles matches our requested structure.
- [] My code additions will fail neither code linting checks nor unit test.
- [] I am only making changes to files I was requested to.

# Screenshots/ Videos

2022-11-29 16:05 UTC, billmal071 commented
You have conflicts.

2022-11-29 16:08 UTC, JulianaSau commented
All these things you created here already exist. All you had to do was edit them. Plus the UI design needs work. If you were using Slack as a reference you completely missed the mark😫

2022-11-29 16:09 UTC, JulianaSau commented
They're located here https://github.com/zurichat/zc_main/blob/dev/packages/ui/src

2022-12-03 21:48 UTC, ickynavigator requested changes

2022-12-03 21:48 UTC, ickynavigator commented on package.json
> +    "react-hook-form": "^7.39.7"
remove these from the root package

2022-12-03 21:48 UTC, ickynavigator commented on packages/main/src/components/channel/addpeople/AddPeople.jsx
> +import Switch from "@mui/material/Switch";
there's already a style library don't install a whole new one

2022-12-03 21:48 UTC, ickynavigator commented on packages/main/src/components/channel/channeldetails/ChannelDetails.jsx
> +import copy from "../../../assets/images/copy.png";
These are things you can get from react icons and style
you are bloating the app

2022-12-03 21:48 UTC, ickynavigator commented on packages/main/src/components/channel/channeldetails/ChannelDetails.jsx
> +            <p>Settings</p>
why are all of these routes linking back to "/"?

2022-12-03 21:48 UTC, ickynavigator commented on packages/main/src/components/channel/createchannel/CreateChannel.jsx
> +import { useForm } from "react-hook-form";
formik is already installed
this package is not necessary

2022-12-03 21:48 UTC, ickynavigator commented on packages/main/src/components/channel/createchannel/createchannel.modeule.css
> +.CreateChannel__wrapper{
you spelt this file wrong it should be `module`

2022-12-03 21:48 UTC, ickynavigator commented on packages/main/src/components/protected/sidebar/components/Room.jsx
> +export default function Room({ items, isOpen, setAddChannel }) {
you added this prop but you are not using it

2022-12-03 21:48 UTC, ickynavigator commented on packages/main/src/components/protected/sidebar/components/Room.jsx
> +      <li> </li>
why did you add an empty `li`?

2022-12-10 10:21 UTC, closed without merging