Fix/profile UI bugs
zurichat/zc_main pull request #2769
Opened 2022-12-01 09:33 UTC by OkoloJohnbosco

# Fixes Issue/Linear Ticket
https://linear.app/team-grit/issue/FRO2-17/zuri-chat-profile-ui-story-point-3

# Changes proposed

1. Reduce the amount of white space
2. Remove the default background from input field
3. Disabled the jumping effect on user preference section

## What did you do?

1. Reduced the amount of white space on the user preference section.
2. Remove the default background from input field on auto fill
3. Disabled the jumping effect on user preference section

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/ Videos
<img width="1440" alt="Screenshot 2022-12-01 at 10 14 44" src="https://user-images.githubusercontent.com/47562075/205013315-72adedbb-bf2d-43ce-bc57-0e3b8143dcfe.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47562075/205016994-f7b62d93-902f-420f-8c59-dc9a1be02cd5.png">

2022-12-01 14:32 UTC, ickynavigator requested changes

2022-12-01 14:32 UTC, ickynavigator commented on packages/main/src/components/protected/topbar/components/TopNavbar.jsx
> +      setUserProfileImage(res?.data?.data?.image_url);
what happens if there is no profile image?
set it to a dummy profile

2022-12-01 14:32 UTC, ickynavigator commented on packages/main/src/components/protected/topbar/styles/NotificationPreference.module.css
> +  /* background-color: red; */
remove commented styles

2022-12-01 14:32 UTC, ickynavigator commented on packages/main/src/components/protected/topbar/styles/NotificationPreference.module.css
> +  /* padding-top: 20px; */
commented styles

2022-12-01 14:32 UTC, ickynavigator commented on packages/main/src/components/protected/topbar/styles/ProfileModal.module.css
> +  /* height: 90vh; */
commented styles

2022-12-01 14:32 UTC, ickynavigator commented on packages/main/src/components/protected/topbar/styles/ProfileModal.module.css
> +  overflow: auto !important;
important?

2022-12-01 14:32 UTC, ickynavigator commented on packages/main/src/components/protected/topbar/styles/ProfileModal.module.css
> +  /* height: 100%; */
commented styles

2022-12-01 21:03 UTC, billmal071 commented
Looks good.

2022-12-02 02:34 UTC, ickynavigator approved these changes

2022-12-02 12:26 UTC, merged