Upgrade for PR #2807 #2823
zurichat/zc_main pull request #2824
Opened 2022-12-09 06:13 UTC by Intuneteq

# Fixes Issue/Linear Ticket

PR fixes approach to #2807 
Though the page still doesn't automatically upload when changes are made to user's profile, user needs to refresh so the avatar will updated in message box
( This could be an existing issue or a linear ticket )

**My PR Closes #issue_number_here** or
**My PR Fixes ID-linear_ticket_number_here**

# Changes proposed

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos
https://drive.google.com/file/d/1u5douG4JWh4uYjDRrHP498lquA1GZNV0/view?usp=drivesdk

2022-12-09 13:08 UTC, billmal071 requested changes

2022-12-09 13:08 UTC, billmal071 commented on packages/utilities/src/workspace.js
> +
remove.

2022-12-09 13:59 UTC, Intuneteq commented
Changes Done

2022-12-10 07:56 UTC, JulianaSau requested changes

2022-12-10 07:56 UTC, JulianaSau commented on packages/main/src/components/protected/topbar/components/TopBarSearchModal.jsx
> +    console.log("filters", filters);
Remove this console.log

2022-12-10 09:30 UTC, Intuneteq commented on packages/main/src/components/protected/topbar/components/TopBarSearchModal.jsx
> +    console.log("filters", filters);
Fixed

2022-12-10 09:50 UTC, JulianaSau approved these changes

2022-12-10 09:50 UTC, merged