Fixed Modal Display Issues on message board as Highlighted by David, HNG 9 Frontend PM for zurichat
zurichat/zc_main pull request #2850
Opened 2022-12-12 12:04 UTC by tryraisins

# Fixes Issue/Linear Ticket

**My PR Fixes The Modal Display Issues as Highlighted by David, HNG 9 Frontend PM for zurichat**

# Changes proposed
Resolve Z-index Conflicts
## What were you told to do?
Fix Edit Workspace Details Modal, Can't close modal after opening

## What did you do?
Removed Z-index property in modalCon class in ModalComponentStyles.module.css file
Removed Z-index property in orgDiv class in Sidebar.module.css file

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

https://user-images.githubusercontent.com/78821732/207040445-9610e299-2f80-4181-bfe8-3825d1954b73.mp4

2022-12-13 17:30 UTC, JulianaSau requested changes

2022-12-13 17:30 UTC, JulianaSau commented on packages/root-config/src/assets/plugin.importmap.json
> +    "@zuri/zuri-plugin-messaging": "//localhost:5013/zuri-messaging.js",
Change this back to the live link

2022-12-13 17:30 UTC, JulianaSau commented on packages/main/src/components/protected/sidebar/styles/Sidebar.module.css
> +  /* z-index: 0; */
Remove this if it's not being used

2022-12-13 17:30 UTC, JulianaSau commented on packages/main/src/components/protected/sidebar/styles/ModalComponentStyles.module.css
> +  /* z-index: 9999; */
Remove this if it's not being used

2022-12-13 18:20 UTC, tryraisins commented on packages/root-config/src/assets/plugin.importmap.json
> +    "@zuri/zuri-plugin-messaging": "//localhost:5013/zuri-messaging.js",
Alright

2022-12-14 15:25 UTC, tryraisins commented on packages/main/src/components/protected/sidebar/styles/ModalComponentStyles.module.css
> +  /* z-index: 9999; */
All changes have been made

2022-12-15 03:12 UTC, JulianaSau approved these changes

2022-12-15 03:45 UTC, merged