My PR Fixes FRO-205 - change organization time zone
zurichat/zc_main pull request #2851
Opened 2022-12-12 16:00 UTC by rambey-coder

# Fixes Issue/Linear Ticket

( This could be an existing issue or a linear ticket )

My PR Fixes FRO-205 - change organization time zone
Linear Ticket link - https://linear.app/team-brainbox/issue/FRO-205/zuri-chat-change-timezone
![Capturex](https://user-images.githubusercontent.com/71680392/207092531-94516c7a-0900-4f33-acbf-dc4058fc3fb9.PNG)

# Changes proposed

## What were you told to do?
Allow organization to change time zones 

## What did you do?

- Check if there is an admin user logged.
- Get the User_id and the organization_id.
- Use these details to change and update the organization time zone in admin setting.
- Make the patch request to the API backend.

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos
![Capturex](https://user-images.githubusercontent.com/71680392/207092699-b4e0f591-a98c-4a26-8fcd-49f23d870f18.PNG)

2022-12-13 17:33 UTC, JulianaSau requested changes

2022-12-13 17:33 UTC, JulianaSau commented on packages/main/src/components/time-zone/TimeZone.jsx
> +        `https://api.zuri.chat/organizations/${organization_id}/members/${user_member_id}/settings`,
Import BASE_API_URL from the utilities package in zc_main

2022-12-13 17:33 UTC, JulianaSau commented on packages/main/src/components/time-zone/TimeZone.jsx
> +        sessionStorage.setItem("user", JSON.stringify(userTimeZone));
You can also add a toast notification to signify that the change has successfully been made

2022-12-17 11:36 UTC, billmal071 requested changes

2022-12-17 11:36 UTC, billmal071 commented on package.json
> -  "dependencies": {}
There's already a toast library installed and this is the wrong place to install it.

2022-12-17 11:36 UTC, billmal071 commented on packages/main/src/components/language/Language.jsx
> +  // }, []);
Remove commented out code.

2022-12-17 11:36 UTC, billmal071 commented on packages/main/src/components/language/Language.jsx
> +  console.log(selectLanguage);
remove commented out code and console.log statements.

2022-12-17 11:36 UTC, billmal071 commented
@rambey-coder

2022-12-22 14:39 UTC, rambey-coder commented on packages/main/src/components/language/Language.jsx
> +  // }, []);
resolved

2022-12-28 08:26 UTC, JulianaSau approved these changes

2022-12-28 08:46 UTC, JulianaSau commented
Hey @rambey-coder, resolve conflicts so that I can merge😅

2022-12-29 05:18 UTC, merged