Fix: Undefined dom Element error fixed on page load
zurichat/zc_main pull request #2855
Opened 2022-12-15 20:05 UTC by sulaimon23

# Fixes Issue/Linear Ticket

( This could be an existing issue or a linear ticket )

**My PR Closes #issue_number_here** or
**My PR Fixes ID-linear_ticket_number_here**

# Changes proposed

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
- [] I am making a pull request against the **dev branch** (left side).
- [] My commit messages styles matches our requested structure.
- [] My code additions will fail neither code linting checks nor unit test.
- [] I am only making changes to files I was requested to.

# Screenshots/ Videos

2022-12-16 19:03 UTC, billmal071 commented
@ickynavigator

2022-12-16 20:05 UTC, ickynavigator requested changes

2022-12-16 20:05 UTC, ickynavigator commented on packages/root-config/src/zuri-root-config.js
> +    element?.remove();
is the element not always available?

2022-12-16 20:05 UTC, ickynavigator commented on packages/ui/src/message-board/MessageBoard.jsx
> +        <div className="MsgBoard" onScroll={e => onHandleScroll(e)}>
this shouldn't be necessary

2022-12-17 14:37 UTC, sulaimon23 commented on packages/root-config/src/zuri-root-config.js
> +    element?.remove();
Yes

2022-12-17 14:41 UTC, sulaimon23 commented on packages/ui/src/message-board/MessageBoard.jsx
> +        <div className="MsgBoard" onScroll={e => onHandleScroll(e)}>
Fixed

2022-12-17 14:44 UTC, sulaimon23 commented
@JulianaSau

2022-12-19 11:45 UTC, ickynavigator approved these changes

2022-12-19 11:46 UTC, merged