Feat/button component
zurichat/zc_main pull request #586
Opened 2021-08-31 12:05 UTC by EstherSeyi

1. **What does this PR Do?** 

> This PR adds a general Button component that has the basic styles of the most common buttons on the app but is flexible and can be styled however you want.

2. **How to test** 

> Pull this branch, import the button component from `./src/components/externalPagesComponent/Button.js` and use it like `<Button>Click Me!</Button>`. 
> The Button component takes a prop **variant** which specifies the button's theme. The prop variant recognizes three values `'primary'`, `'secondary'`, and `'accent'`. By default `variant=" primary"`, and the button has the primary styles.  `variant = "secondary"` will add secondary styles and `variant ="accent"` will add no styles besides the default button styles, leaving it bare for you to style yourself. 
> You can extend the styles using className or style prop like normal and you can use all the attributes that a regular button can use.

3. **Screenshots?**
<img width="377" alt="Screenshot 2021-08-31 at 12 47 41" src="https://user-images.githubusercontent.com/40301524/131498711-089741ff-b661-4666-9917-ba9e123fc326.png">
<img width="377" alt="Screenshot 2021-08-31 at 12 45 35" src="https://user-images.githubusercontent.com/40301524/131498728-e996b6f8-dfa6-44aa-8c73-e5b8f53f5680.png">
<img width="377" alt="Screenshot 2021-08-31 at 12 45 50" src="https://user-images.githubusercontent.com/40301524/131498760-f950bb61-c503-4915-97a2-b630701d7875.png">

2021-08-31 12:17 UTC, pidoxy requested changes
Add the following:
* A live link
* onChange prop for the button to take in a function
* A isDisabled boolean prop to disable the button or not

Your live link should take in a function that prints something in the console

2021-08-31 17:33 UTC, okerekechinweotito requested changes
I still can't see any onChange prop and isDisabled boolean prop

2021-08-31 19:13 UTC, EstherSeyi commented
> I still can't see any onChange prop and isDisabled boolean prop

There's no need for that, you can use any attribute you'd use on a regular button. I already discussed this with pidoxy.

2021-09-02 09:55 UTC, seunbayo commented
resolve conflicts

2021-09-03 15:41 UTC, closed without merging